apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-job-name
spec:
  template:
    metadata:
      name: countdown-job-name
    spec:
      restartPolicy: Never
      containers:
      - name: container-countdown-job-name
        image: ubuntu:latest
        command:
        - sleep
        - "5"