apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-nautilus
spec:
  template:
    metadata:
      name: countdown-nautilus
    spec:
      restartPolicy: Never
      containers:
      - name: container-countdown-nautilus
        image: ubuntu:latest
        command:
        - sleep
        - "5"